"""add registration_requests and user fields

Revision ID: c32a0ce0c443
Revises:
Create Date: 2026-08-11 12:42:19.896615
"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "c32a0ce0c443"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_users_username",
            ["username"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_users_username",
            type_="unique",
        )

    # ### end Alembic commands ###